### ISSUE TITLE
AutoPi - 404 error

### ISSUE THREAD

**Issue by Dinth** [alexanv1/customcomponents#3]
Hi. I know that you dont want to support AutoPi integration, but i was wondering if it still works for you?
Since recently, im constantly getting this error:
Error setting up entry AutoPi for autopi
```
5:15:54 PM – (ERROR) AutoPi (custom integration) - message first occurred at 8:14:26 AM and shows up 2 times
2010 Honda CR-V - getting position failed. Status = 404, response = <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
5:15:54 PM – (ERROR) AutoPi (custom integration) - message first occurred at 8:14:26 AM and shows up 2 times
```

**Comment by alexanv1** [comment]
Hmmm, yes, it works for me. Can you please double-check that you running the latest version of the code (I haven't updated in 6 months but just to be sure).

Also, if you could turn up the logging for the integration to debug and send me the log, perhaps that will have some clues.

**Comment by Dinth** [comment]
Here is the log with debug enabled (I have only removed some sensitive personal info)
```
2022-07-27 11:28:25 INFO (SyncWorker_2) [custom_components.autopi] 2010 Honda CR-V - getting position failed, will retry. Status = 404, response = <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
2022-07-27 11:28:25 INFO (SyncWorker_2) [custom_components.autopi] Logging in to AutoPi.
2022-07-27 11:28:26 INFO (SyncWorker_2) [custom_components.autopi] Received login response json = {'token': 'XXX', 'user': {'pk': 2631, 'username': 'michal', 'email': 'XXX', 'first_name': 'Michal', 'last_name': 'XXX', 'countryISO': 'GB', 'street': '', 'streetNo': '', 'city': '', 'postalCode': '', 'is_verified': True, 'has_devices': True, 'devices': [{'id': '3a433a2f-d7a2-4dc9-827b-bb7122dc9ffc', 'unit_id': '4c444991-985f-055f-cee2-42f522999330', 'owner': 4660, 'display': 'Honda CR-V', 'vehicle': {'id': 1526, 'vin': None, 'display': 'Honda CR-V', 'callName': 'Honda CR-V', 'licensePlate': None, 'model': 285, 'make': 18, 'year': 2010, 'type': 'ICE', 'battery_nominal_voltage': 12}, 'template': None, 'last_communication': '2022-07-26T13:23:15.045838Z'}], 'has_pending_terms': False, 'groups': ['FullDeviceAccess'], 'addons': [{'slug': 'troublecodes', 'settings': {}}, {'slug': 'cananalyzer', 'settings': {}}], 'timezone': 'Europe/London', 'use_metric_format': True, 'use_24_hour_format': True, 'dashboards': [{'id': 1795, 'default': False}]}}
2022-07-27 11:28:26 ERROR (SyncWorker_2) [custom_components.autopi] 2010 Honda CR-V - getting position failed. Status = 404, response = <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
2022-07-27 11:28:26 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry AutoPi for autopi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/autopi/__init__.py", line 45, in async_setup_entry
    await hass.async_add_executor_job(autoPIDevice.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/autopi/__init__.py", line 152, in update
    self._get_vehicle_data()
  File "/config/custom_components/autopi/__init__.py", line 184, in _get_vehicle_data
    position = self._get_position()
  File "/config/custom_components/autopi/__init__.py", line 177, in _get_position
    position_response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.autopi.io/logbook/most_recent_position/?device_id=3a433a2f-d7a2-4dc9-827b-bb7122dc9ffc
```

**Comment by alexanv1** [comment]
Yeah, you're using an older version of the code and I guess AutoPI turned off the older endpoint now.
In the log, it's trying to connect to pull positions from https://api.autopi.io/logbook/most_recent_position
In the latest, the URL is https://api.autopi.io/logbook/v2/most_recent_position

I think if you use the latest version, it will all work.

**Comment by Dinth** [comment]
Amazing, thank you and sorry for the hassle. I actually have updated the integration about 6 months ago (probably just before you published the latest version) so whenever i was checking for a new version i thought i already have it.
